[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false