[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

optimizer = true
optimizer_runs = 200

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false